package laws

import java.io.File
import IO._

object Laws {
  def main(args: Array[String]) {
    val Seq(outDirPath, template) = args.toSeq
    val replaced = read(new File(template)).replaceAllLiterally("@FOO@", "42")
    val content = "// Generated by laws.Laws\n" + replaced
    write(new File(outDirPath), content)
  }
}


object IO {
  def read(file: File): String = {
    scala.io.Source.fromFile(file).mkString
  }

  def write(file: File, contents: String) = printToFile(file)(_.write(contents))

  def printToFile(f: File)(op: java.io.PrintWriter => Unit) {
    val p = new java.io.PrintWriter(f)
    try { op(p) } finally { p.close() }
  }
}
